name: TangAndPivot
favicon: null
layout_spectrum: 0.0942
typography_spectrum: 0.50457
title: 'Tang & Pivot'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5187906
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
