name: TangAndPivot
favicon: null
layout_spectrum: 0.98035
typography_spectrum: 0.51231
title: 'Tang & Pivot'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b2bed4'
    - '#959591'
    - '#4c4942'
    - '#ac3334'
    - '#e75f5b'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
